### ISSUE TITLE
Combine Options deprecated

### ISSUE THREAD

**Issue by rbarisic-lme** [Dreamersoul/administrate-field-active_storage#133]
My attached image doesn't render after saving a model (e.g. profile)
I get this error in the network tab of the image's request:

```
ArgumentError at /rails/active_storage/representations/redirect/<jwttoken>/<filename>.png
======================================================================================================================================================================================================================================================================================================================================================================================================================================================================

Active Storage's ImageProcessing transformer doesn't support :combine_options, as it always generates a single command.

> To access an interactive console with this error, point your browser to: /__better_errors


activestorage (7.0.4.3) lib/active_storage/transformers/image_processing_transformer.rb, line 39
------------------------------------------------------------------------------------------------

``` ruby
   34               if ActiveStorage.variant_processor == :mini_magick
   35                 validate_transformation(name, argument)
   36               end
   37   
   38               if name.to_s == "combine_options"
>  39                 raise ArgumentError, <<~ERROR.squish
   40                   Active Storage's ImageProcessing transformer doesn't support :combine_options,
   41                   as it always generates a single command.
   42                 ERROR
   43               end
   44   
```

App backtrace
-------------

Full backtrace
--------------

 - activestorage (7.0.4.3) lib/active_storage/transformers/image_processing_transformer.rb:39:in `block in operations'
 - activestorage (7.0.4.3) lib/active_storage/transformers/image_processing_transformer.rb:33:in `operations'
 - activestorage (7.0.4.3) lib/active_storage/transformers/image_processing_transformer.rb:24:in `process'
 - activestorage (7.0.4.3) lib/active_storage/transformers/transformer.rb:22:in `transform'
 - activestorage (7.0.4.3) app/models/active_storage/variation.rb:56:in `block in transform'
 - activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
 - activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 - activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
 - activestorage (7.0.4.3) app/models/active_storage/variation.rb:55:in `transform'
 - activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:35:in `block in transform_blob'
 - activestorage (7.0.4.3) lib/active_storage/downloader.rb:15:in `block in open'
 - activestorage (7.0.4.3) lib/active_storage/downloader.rb:24:in `open_tempfile'
 - activestorage (7.0.4.3) lib/active_storage/downloader.rb:12:in `open'
 - activestorage (7.0.4.3) lib/active_storage/service.rb:90:in `open'
 - activestorage (7.0.4.3) app/models/active_storage/blob.rb:301:in `open'
 - activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'
 - activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:19:in `process'
 - activestorage (7.0.4.3) app/models/active_storage/variant_with_record.rb:14:in `processed'
 - activestorage (7.0.4.3) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:400:in `block in make_lambda'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
 - actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:200:in `block in halting'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `block in invoke_before'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:595:in `invoke_before'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
 - actiontext (7.0.4.3) lib/action_text/rendering.rb:20:in `with_renderer'
 - actiontext (7.0.4.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
 - actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
 - actionpack (7.0.4.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
 - actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
 - activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
 - activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 - activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
 - actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
 - actionpack (7.0.4.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
 - activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 - actionpack (7.0.4.3) lib/abstract_controller/base.rb:151:in `process'
 - actionview (7.0.4.3) lib/action_view/rendering.rb:39:in `process'
 - actionpack (7.0.4.3) lib/action_controller/metal.rb:188:in `dispatch'
 - actionpack (7.0.4.3) lib/action_controller/metal.rb:251:in `dispatch'
 - actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 - actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 - actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 - actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
 - actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
 - bullet (7.0.7) lib/bullet/rack.rb:17:in `call'
 - clearance (2.6.1) lib/clearance/rack_session.rb:23:in `call'
 - rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
 - rack (2.2.7) lib/rack/etag.rb:27:in `call'
 - rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
 - rack (2.2.7) lib/rack/head.rb:12:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
 - rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
 - rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/cookies.rb:704:in `call'
 - activerecord (7.0.4.3) lib/active_record/migration.rb:603:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 - activesupport (7.0.4.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
 - better_errors (2.10.0) lib/better_errors/middleware.rb:87:in `protected_app_call'
 - better_errors (2.10.0) lib/better_errors/middleware.rb:82:in `better_errors_call'
 - better_errors (2.10.0) lib/better_errors/middleware.rb:60:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
 - web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
 - web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
 - railties (7.0.4.3) lib/rails/rack/logger.rb:40:in `call_app'
 - railties (7.0.4.3) lib/rails/rack/logger.rb:27:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
 - rack (2.2.7) lib/rack/method_override.rb:24:in `call'
 - rack (2.2.7) lib/rack/runtime.rb:22:in `call'
 - activesupport (7.0.4.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - rack-livereload (0.5.1) lib/rack/livereload.rb:23:in `_call'
 - rack-livereload (0.5.1) lib/rack/livereload.rb:14:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
 - rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
 - actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
 - railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
 - rack (2.2.7) lib/rack/handler/webrick.rb:95:in `service'
 - webrick (1.8.1) lib/webrick/httpserver.rb:140:in `service'
 - webrick (1.8.1) lib/webrick/httpserver.rb:96:in `run'
 - webrick (1.8.1) lib/webrick/server.rb:310:in `block in start_thread'

```

**Comment by Dreamersoul** [comment]
Hello, we haven't used combined options for years now, could you try cleaning up bundle gems? Also is this error showing up when you browse the index of the admin panel model? Or details?
