### ISSUE TITLE
Breaks with Rails 7.1

### ISSUE THREAD

**Issue by migu0** [Dreamersoul/administrate-field-active_storage#134]
After upgrading to Rails 7.1, this gem no longer seems to work. I get the following error when editing a record and attaching an image to it:

```
ActiveStorage::Attachment Load (0.4ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3  [["record_id", "0b689cc7-bb77-4a52-bef4-469647852a66"], ["record_type", "Label"], ["name", "sample_images"]]
Label Exists? (0.3ms)  SELECT 1 AS one FROM "labels" WHERE "labels"."name_android" = $1 AND "labels"."id" != $2 LIMIT $3  [["name_android", ""], ["id", "0b689cc7-bb77-4a52-bef4-469647852a66"], ["LIMIT", 1]]
TRANSACTION (0.2ms)  ROLLBACK
Rendering layout layouts/admin/application.html.erb
Rendering vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/administrate/application/edit.html.erb within layouts/admin/application
LabelGroup Load (0.3ms)  SELECT "label_groups".* FROM "label_groups" WHERE "label_groups"."id" = $1 LIMIT $2  [["id", "07b5e687-0e28-4186-91ea-e3942219998e"], ["LIMIT", 1]]
LabelGroup Load (0.5ms)  SELECT "label_groups".* FROM "label_groups"
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/belongs_to/_form.html.erb (Duration: 2.0ms | Allocations: 2064)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/number/_form.html.erb (Duration: 0.2ms | Allocations: 205)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/string/_form.html.erb (Duration: 0.2ms | Allocations: 205)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/string/_form.html.erb (Duration: 0.5ms | Allocations: 761)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/text/_form.html.erb (Duration: 0.2ms | Allocations: 200)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/string/_form.html.erb (Duration: 0.2ms | Allocations: 201)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/boolean/_form.html.erb (Duration: 0.2ms | Allocations: 210)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/boolean/_form.html.erb (Duration: 0.2ms | Allocations: 211)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/boolean/_form.html.erb (Duration: 0.2ms | Allocations: 211)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/fields/has_many/_form.html.erb (Duration: 4.2ms | Allocations: 4953)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-select-2.1.0/app/views/fields/select_basic/_form.html.erb (Duration: 0.3ms | Allocations: 248)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-select-2.1.0/app/views/fields/select_basic/_form.html.erb (Duration: 0.2ms | Allocations: 242)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-active_storage-0.4.2/app/views/fields/active_storage/_preview.html.erb (Duration: 0.4ms | Allocations: 299)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-active_storage-0.4.2/app/views/fields/active_storage/_item.html.erb (Duration: 0.5ms | Allocations: 358)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-active_storage-0.4.2/app/views/fields/active_storage/_items.html.erb (Duration: 0.6ms | Allocations: 420)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-field-active_storage-0.4.2/app/views/fields/active_storage/_form.html.erb (Duration: 0.8ms | Allocations: 640)
Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/administrate/application/_form.html.erb (Duration: 12.7ms | Allocations: 12500)
   Rendered vendor/bundle/ruby/3.2.0/gems/administrate-0.19.0/app/views/administrate/application/edit.html.erb within layouts/admin/application (Duration: 13.8ms | Allocations: 14490)
  Rendered layout layouts/admin/application.html.erb (Duration: 13.9ms | Allocations: 14550)
Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.5ms | Allocations: 18118)
[05f534c2-a275-40e0-8dcd-965cd52bb7ec]
ActionView::Template::Error (Cannot get a signed_id for a new record):
    2:   <% if attachment.image? %>
    3:     <% if attachment.variable? %>
    4:       <% if variant.nil? %>
    5:         <%= image_tag(field.variant(attachment, resize_to_limit: size)) %>
    6:       <% else %>
    7:         <%= image_tag(attachment.variant(variant)) %>
    8:       <% end %>
[05f534c2-a275-40e0-8dcd-965cd52bb7ec]
activerecord (7.1.0) lib/active_record/signed_id.rb:113:in `signed_id'
activestorage (7.1.0) app/models/active_storage/blob.rb:162:in `signed_id'
activestorage (7.1.0) config/routes.rb:71:in `block (2 levels) in <main>'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:679:in `instance_exec'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:679:in `eval_block'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:668:in `call'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:162:in `block (2 levels) in add_url_helper'
actionpack (7.1.0) lib/action_dispatch/routing/url_for.rb:218:in `public_send'
actionpack (7.1.0) lib/action_dispatch/routing/url_for.rb:218:in `route_for'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:545:in `route_for'
activestorage (7.1.0) config/routes.rb:19:in `block (2 levels) in <main>'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:679:in `instance_exec'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:679:in `eval_block'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:668:in `call'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:156:in `block (2 levels) in add_url_helper'
administrate-field-active_storage (0.4.2) lib/administrate/field/active_storage.rb:62:in `variant'
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_preview.html.erb:5
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:24:in `render'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:37:in `block in render'
actionview (7.1.0) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:33:in `render'
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_item.html.erb:28
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:24:in `render'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:37:in `block in render'
actionview (7.1.0) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:33:in `render'
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_items.html.erb:28
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_items.html.erb:26:in `each'
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_items.html.erb:26
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:24:in `render'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:37:in `block in render'
actionview (7.1.0) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:33:in `render'
administrate-field-active_storage (0.4.2) app/views/fields/active_storage/_form.html.erb:24
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:24:in `render'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:37:in `block in render'
actionview (7.1.0) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:33:in `render'
administrate (0.19.0) app/helpers/administrate/application_helper.rb:12:in `render_field'
administrate (0.19.0) app/views/administrate/application/_form.html.erb:38
administrate (0.19.0) app/views/administrate/application/_form.html.erb:36:in `each'
administrate (0.19.0) app/views/administrate/application/_form.html.erb:36
actionview (7.1.0) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.0) lib/action_view/buffers.rb:75:in `capture'
actionview (7.1.0) lib/action_view/helpers/capture_helper.rb:50:in `capture'
actionview (7.1.0) lib/action_view/helpers/form_helper.rb:773:in `form_with'
actionview (7.1.0) lib/action_view/helpers/form_helper.rb:461:in `form_for'
administrate (0.19.0) app/views/administrate/application/_form.html.erb:17
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:252:in `block in render_partial_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.1.0) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:55:in `render_partial'
actionview (7.1.0) lib/action_view/helpers/rendering_helper.rb:44:in `render'
administrate (0.19.0) app/views/administrate/application/edit.html.erb:35
actionview (7.1.0) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.0) lib/action_view/base.rb:264:in `_run'
actionview (7.1.0) lib/action_view/template.rb:254:in `block in render'
activesupport (7.1.0) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.1.0) lib/action_view/template.rb:535:in `instrument_render_template'
actionview (7.1.0) lib/action_view/template.rb:248:in `render'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.1.0) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:63:in `render_template_to_object'
actionview (7.1.0) lib/action_view/renderer/renderer.rb:31:in `render_to_object'
actionview (7.1.0) lib/action_view/rendering.rb:135:in `block in _render_template'
actionview (7.1.0) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.0) lib/action_view/rendering.rb:134:in `_render_template'
actionpack (7.1.0) lib/action_controller/metal/streaming.rb:256:in `_render_template'
actionview (7.1.0) lib/action_view/rendering.rb:121:in `render_to_body'
actionpack (7.1.0) lib/action_controller/metal/rendering.rb:158:in `render_to_body'
actionpack (7.1.0) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (7.1.0) lib/abstract_controller/rendering.rb:27:in `render'
actionpack (7.1.0) lib/action_controller/metal/rendering.rb:139:in `render'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:29:in `block (2 levels) in render'
vendor/ruby-3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
activesupport (7.1.0) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:29:in `block in render'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:98:in `cleanup_view_runtime'
activerecord (7.1.0) lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:28:in `render'
administrate (0.19.0) app/controllers/administrate/application_controller.rb:65:in `update'
actionpack (7.1.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.1.0) lib/abstract_controller/base.rb:224:in `process_action'
actionpack (7.1.0) lib/action_controller/metal/rendering.rb:165:in `process_action'
actionpack (7.1.0) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
activesupport (7.1.0) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
actiontext (7.1.0) lib/action_text/rendering.rb:23:in `with_renderer'
actiontext (7.1.0) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.1.0) lib/active_support/callbacks.rb:130:in `instance_exec'
activesupport (7.1.0) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
activesupport (7.1.0) lib/active_support/callbacks.rb:141:in `run_callbacks'
actionpack (7.1.0) lib/abstract_controller/callbacks.rb:258:in `process_action'
actionpack (7.1.0) lib/action_controller/metal/rescue.rb:25:in `process_action'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
actionpack (7.1.0) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
activerecord (7.1.0) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
actionpack (7.1.0) lib/abstract_controller/base.rb:160:in `process'
actionview (7.1.0) lib/action_view/rendering.rb:40:in `process'
actionpack (7.1.0) lib/action_controller/metal.rb:227:in `dispatch'
actionpack (7.1.0) lib/action_controller/metal.rb:309:in `dispatch'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.1.0) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.0) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.0) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.0) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:882:in `call'
rack (3.0.8) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.0.8) lib/rack/etag.rb:29:in `call'
rack (3.0.8) lib/rack/conditional_get.rb:43:in `call'
rack (3.0.8) lib/rack/head.rb:15:in `call'
actionpack (7.1.0) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.0) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/cookies.rb:689:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.0) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.0) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.0) lib/active_support/tagged_logging.rb:135:in `block in tagged'
activesupport (7.1.0) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.0) lib/active_support/tagged_logging.rb:135:in `tagged'
activesupport (7.1.0) lib/active_support/broadcast_logger.rb:212:in `method_missing'
railties (7.1.0) lib/rails/rack/logger.rb:24:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.0.8) lib/rack/method_override.rb:28:in `call'
rack (3.0.8) lib/rack/runtime.rb:24:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.0) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.0.8) lib/rack/sendfile.rb:114:in `call'
railties (7.1.0) lib/rails/engine.rb:529:in `call'
puma (6.4.0) lib/puma/configuration.rb:272:in `call'
puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
puma (6.4.0) lib/puma/server.rb:443:in `process_client'
puma (6.4.0) lib/puma/server.rb:241:in `block in run'
puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by Dreamersoul** [comment]
Huh weird, I have it running just fine at 7.0.X but I think 7.1.0 breaks the gem.
If you figure it out let me know, I'll try to take a look soon

**Comment by migu0** [comment]
Thanks, I'll have another look in a few days. It worked locally but not on Heroku after upgrading to 7.1 so maybe the problem is somewhere different. Will keep you posted.

**Comment by littleforest** [comment]
I'm also getting this error trying to upgrade to Rails 7.1: `ActionView::Template::Error (Cannot get a signed_id for a new record)`.
