### ISSUE TITLE
Preview does not appear

### ISSUE THREAD

**Issue by damienlethiec** [Dreamersoul/administrate-field-active_storage#39]
Hi there,

I have a small problem with preview. Nothing appears in my admin (small in show, index, edit, etc.). Do you have an idea why?

My code:

```
has_one_attached :image
```

```
  ATTRIBUTE_TYPES = {
    product: Field::BelongsTo,
    image: Field::ActiveStorage,
    id: Field::Number,
    source: Field::String,
    source_url: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

...

  SHOW_PAGE_ATTRIBUTES = %i[
  product
  image
  id
  source
  source_url
  created_at
  updated_at
  ].freeze
```

![image](https://user-images.githubusercontent.com/8105430/79983244-c2c02a80-84a7-11ea-89ac-c4e6c49b5537.png)

**Comment by Dreamersoul** [comment]
Do you have the`image_processing` gem installed?

**Comment by damienlethiec** [comment]
Yes, I have :)

**Comment by Dreamersoul** [comment]
can you track down the error that shows up in the console? also which version do you have installed?

**Comment by damienlethiec** [comment]
My version are:
"image_processing", "~> 1.9", ">= 1.9.2"
"administrate", github: "excid3/administrate", branch: "jumpstart"
"administrate-field-active_storage", "~> 0.3.2"

Sure, here it is:


```
b     | actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
web     | actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
web     | actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
web     | actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
web     | actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
web     | actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
web     | bullet (6.1.0) lib/bullet/rack.rb:15:in `call'
web     | warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
web     | warden (1.2.8) lib/warden/manager.rb:34:in `catch'
web     | warden (1.2.8) lib/warden/manager.rb:34:in `call'
web     | rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
web     | rack (2.2.2) lib/rack/etag.rb:27:in `call'
web     | rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
web     | rack (2.2.2) lib/rack/head.rb:12:in `call'
web     | actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
web     | rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
web     | rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
web     | actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
web     | activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'
web     | actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web     | activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
web     | actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web     | actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
web     | actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web     | rollbar (2.24.0) lib26ollbar0 iddlewar32rails/r8llba7.14:25:13 76lock in call'
web     | rollbar (2.24.0) lib/rollbar.rb:145:in `scoped'
stripe  | [Wed, 22 Apr 2020 16:11:30 CEST] ERROR read error: read tcp 192.168.1.98:59576->54.187.119.242:443: i/o timeout
web     | Started GET "/admin/product_images/6646" for 77.134.181.173 at 2020-04-22 16:11:43 +0200
web     | Cannot render console from 77.134.181.173! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web     |   User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
web     | Processing by Admin::ProductImagesController#show as HTML Server Error'
web     |   Parameters: {"id"=>"6646"}console/middlewa 500 Internal Server Error
web     |   ProductImage Load (1.3ms)  SELECT "product_images".* FROM "product_images" WHERE "product_images"."id" = $1 LIMIT $2  [["id", 6646], ["LIMIT", 1]]
web     |   ActiveStorage::Attachment Load (0.8ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = $1 AND "active_storage_attachments"."name" = $2 AND "active_storage_attachments"."record_id" = $3  [["record_type", "ProductImage"], ["name", "image"], ["record_id", 6646]]
web     |   ActiveStorage::Blob Load (0.4ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1  [["id", 9628]]
web     |   Rendering /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-66fccf11506d/app/views/administrate/application/show.html.erb within layouts/admin/application.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
web     |   Product Load (1.0ms)  SELECT "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 3150], ["LIMIT", 1]]
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-66fccf11506d/app/views/fields/belongs_to/_show.html.erb (Duration: 4.7ms | Allocations: 487).2.2) lib/rails/rack/logger.rb:26:in `call'
web     |   ActiveStorage::Attachment Load (0.2ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."blob_id" = $1  [["blob_id", 9628]]ionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/gems/administrate-field-active_storage-0.3.2/app/views/fields/active_storage/_preview.html.erb (Duration: 2.9ms | Allocations: 652)ction_dispatch/middleware/request_id.rb:27:in `call'
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/gems/administrate-field-active_storage-0.3.2/app/views/fields/active_storage/_item.html.erb (Duration: 681.8ms | Allocations: 173783)e.rb:22:in `call'
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/gems/administrate-field-active_storage-0.3.2/app/views/fields/active_storage/_items.html.erb (Duration: 691.9ms | Allocations: 177273)on_dispatch/middleware/executor.rb:14:in `call'
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/gems/administrate-field-active_storage-0.3.2/app/views/fields/active_storage/_show.html.erb (Duration: 695.3ms | Allocations: 178249)le.rb:110:in `call'
web     |   Rendered /usr/local/Cellar/rbenv/1.1.2/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-66fccf11506d/app/views/administrate/application/show.html.erb within layouts/admin/application (Duration: 721.0ms | Allocations: 184830) `perform_request'
web     | Completed 500 Internal Server Error in 749ms (ActiveRecord: 3.9ms | Allocations: 193460)
web     | railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
web     | puma (4.3.3) lib/puma/configuration.rb:228:in `call'
web     |   ma (4.3.3) lib/puma/server.rb:682:in `handle_request'
web     | ActionView::Template::Error (undefined method `image_admin_product_image_path' for #<#<Class:0x00007fcff43ba418>:0x00007fcff966a6b8>
web     | Did you mean?  edit_admin_product_image_path):in run'
web     |     36: <% if field.destroy_url.present? %> `block in spawn_thread'
web     |     37:   <% destroy_url = field.destroy_url.call(namespace, field.data.record, attachment) %>
web     |     38:   <div>
web     |     39:     <%= link_to 'Remove', destroy_url, method: :delete, class: 'remove-attachment-link' %>
web     |     40:   </div>
web     |     41:   <hr>
web     |     42: <% end %>
web     |
web     | actionpack (6.0.2.2) lib/action_dispatch/routing/polymorphic_routes.rb:233:in `polymorphic_method'
web     | actionpack (6.0.2.2) lib/action_dispatch/routing/polymorphic_routes.rb:139:in `polymorphic_path'
web     | actionview (6.0.2.2) lib/action_view/routing_url_for.rb:102:in `url_for'
web     | actionview (6.0.2.2) lib/action_view/helpers/url_helper.rb:202:in `link_to'
web     | administrate-field-active_storage (0.3.2) app/views/fields/active_storage/_item.html.erb:39
web     | actionview (6.0.2.2) lib/action_view/base.rb:274:in `_run'
web     | actionview (6.0.2.2) lib/action_view/template.rb:185:in `block in render'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:182:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/template.rb:386:in `instrument_render_template'
web     | actionview (6.0.2.2) lib/action_view/template.rb:183:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:358:in `block in render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:347:in `render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:317:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:22:in `render'
web     | actionview (6.0.2.2) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
web     | actionview (6.0.2.2) lib/action_view/base.rb:304:in `in_rendering_context'
web     | actionview (6.0.2.2) lib/action_view/helpers/rendering_helper.rb:30:in `render'
web     | administrate-field-active_storage (0.3.2) app/views/fields/active_storage/_items.html.erb:22
web     | activerecord (6.0.2.2) lib/active_record/relation/delegation.rb:85:in `each'
web     | activerecord (6.0.2.2) lib/active_record/relation/delegation.rb:85:in `each'
web     | administrate-field-active_storage (0.3.2) app/views/fields/active_storage/_items.html.erb:20
web     | actionview (6.0.2.2) lib/action_view/base.rb:274:in `_run'
web     | actionview (6.0.2.2) lib/action_view/template.rb:185:in `block in render'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:182:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/template.rb:386:in `instrument_render_template'
web     | actionview (6.0.2.2) lib/action_view/template.rb:183:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:358:in `block in render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:347:in `render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:317:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:22:in `render'
web     | actionview (6.0.2.2) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
web     | actionview (6.0.2.2) lib/action_view/base.rb:304:in `in_rendering_context'
web     | actionview (6.0.2.2) lib/action_view/helpers/rendering_helper.rb:30:in `render'
web     | administrate-field-active_storage (0.3.2) app/views/fields/active_storage/_show.html.erb:19
web     | actionview (6.0.2.2) lib/action_view/base.rb:274:in `_run'
web     | actionview (6.0.2.2) lib/action_view/template.rb:185:in `block in render'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:182:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/template.rb:386:in `instrument_render_template'
web     | actionview (6.0.2.2) lib/action_view/template.rb:183:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:358:in `block in render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web     | activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:347:in `render_partial'
web     | actionview (6.0.2.2) lib/action_view/renderer/partial_renderer.rb:317:in `render'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
web     | actionview (6.0.2.2) lib/action_view/renderer/renderer.rb:22:in `render'
web     | actionview (6.0.2.2) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
web     | actionview (6.0.2.2) lib/action_view/base.rb:304:in `in_rendering_context'
web     | actionview (6.0.2.2) lib/action_
```

**Comment by Dreamersoul** [comment]
looks like you did not define a destroy path this could be a bug ill look into it, but currently as a quickfix do the following:
```ruby
 ATTRIBUTE_TYPES = {
    product: Field::BelongsTo,
    image: Field::ActiveStorage.with_options(destroy_url: nil,),
    id: Field::Number,
    source: Field::String,
    source_url: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze
```

**Comment by damienlethiec** [comment]
It fixed an other bug (could not accesss the show) but I still have the preview problem

**Comment by damienlethiec** [comment]
My logs now:

```

**Comment by damienlethiec** [comment]
For info, the images display correctly in other pages with an image_tag

**Comment by Dreamersoul** [comment]
> My logs now:
> 
> ```
> web     | MiniMagick::Error (`convert /var/folders/d_/7js_0w614c3_7hmhngv3zhvw0000gn/T/ActiveStorage-9620-20200422-67875-1jilc8r.jpg[0] -auto-orient -resize 150x150> -sharpen 0x1 /var/folders/d_/7js_0w614c3_7hmhngv3zhvw0000gn/T/image_processing20200422-67875-holqtr.jpg` failed with error:
> web     | convert: unable to load module `/usr/local/Cellar/imagemagick/6.9.5-8/lib/ImageMagick//modules-Q16/coders/jpeg.la': file not found @ error/module.c/OpenModule/1302.
> web     | convert: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/504.
> web     | convert: no images defined `/var/folders/d_/7js_0w614c3_7hmhngv3zhvw0000gn/T/image_processing20200422-67875-holqtr.jpg' @ error/convert.c/ConvertImageCommand/3257.
> web     | ):
> ```

this says that there is an issue with imagemagik can you check this answer? https://stackoverflow.com/a/22716937/3065081

**Comment by damienlethiec** [comment]
thanks, I will try

**Comment by Dreamersoul** [comment]
you're welcome!
